export const FETCH_CREATE_POKEMON_REQUEST = 'FETCH_CREATE_POKEMON_REQUEST';
export const FETCH_CREATE_POKEMON_SUCCESS = 'FETCH_CREATE_POKEMON_SUCCESS';
export const FETCH_CREATE_POKEMON_ERROR = 'FETCH_CREATE_POKEMON_ERROR';

export const FETCH_READ_POKEMONS_REQUEST = 'FETCH_READ_POKEMONS_REQUEST';
export const FETCH_READ_POKEMONS_SUCCESS = 'FETCH_READ_POKEMONS_SUCCESS';
export const FETCH_READ_POKEMONS_ERROR = 'FETCH_READ_POKEMONS_ERROR';

export const FETCH_READ_POKEMON_REQUEST = 'FETCH_READ_POKEMON_REQUEST';
export const FETCH_READ_POKEMON_SUCCESS = 'FETCH_READ_POKEMON_SUCCESS';
export const FETCH_READ_POKEMON_ERROR = 'FETCH_READ_POKEMON_ERROR';

export const FETCH_UPDATE_POKEMON_REQUEST = 'FETCH_UPDATE_POKEMON_REQUEST';
export const FETCH_UPDATE_POKEMON_SUCCESS = 'FETCH_UPDATE_POKEMON_SUCCESS';
export const FETCH_UPDATE_POKEMON_ERROR = 'FETCH_UPDATE_POKEMON_ERROR';

export const FETCH_DELETE_POKEMON_REQUEST = 'FETCH_DELETE_POKEMON_REQUEST';
export const FETCH_DELETE_POKEMON_SUCCESS = 'FETCH_DELETE_POKEMON_SUCCESS';
export const FETCH_DELETE_POKEMON_ERROR = 'FETCH_DELETE_POKEMON_ERROR';