export const FETCH_CREATE_POKEMON_REQUEST = 'FETCH_CREATE_POKEMON_REQUEST';
export const FETCH_CREATE_POKEMON_SUCCESS = 'FETCH_CREATE_POKEMON_SUCCESS';
export const FETCH_CREATE_POKEMON_ERROR = 'FETCH_CREATE_POKEMON_ERROR';

export const FETCH_READ_POKEMONS_REQUEST = 'FETCH_READ_POKEMONS_REQUEST';
export const FETCH_READ_POKEMONS_SUCCESS = 'FETCH_READ_POKEMONS_SUCCESS';
export const FETCH_READ_POKEMONS_ERROR = 'FETCH_READ_POKEMONS_ERROR';